### ISSUE TITLE
HTML files open with Vue Component syntax highlighting

### ISSUE THREAD

**Issue by virzen** [CYBAI/language-vue-component#12]
At the moment of writing, Atom with `language-vue-component` (v0.4.4) improperly recognizes `.html` files as Vue Components and opens them with `Vue Component` syntax highlighting. This behaviour leads to switching syntax every time user opens a HTML file, even if it's the usual, not-component one. Thus, I think it should be disabled.

I have found out it can be accomplished by deleting 6th line from `grammars/vue.cson` file, i. e.

```
'fileTypes': [
  'vue'
  'vue.html'
  'html' // this one
]
```

I'm willing create pull request if there is anyone who's going to accept it.

EDIT:
I have created a PR - #13.

**Comment by Virzen** [comment]
Thank you for accepting PR. I'm closing the issue.

**Comment by virzen** [comment]
Issue fixed in #13.
