### ISSUE TITLE
I made one too :)

### ISSUE THREAD

**Issue by hedefalk** [CYBAI/language-vue-component#2]
Hi,

I made the mistake of not googling and before finding this project I went ahead and made an automatic conversion from 

https://github.com/vuejs/vue-syntax-highlight/commit/479672799b4162996e3c3c7e09583fb6d98e1e6c 

with apm (via textmate according to https://discuss.atom.io/t/convert-sublime-grammar-to-atom-grammar/14843.)

I haven't even figured out if everything worked, but I noticed a difference that I don't get any colors in html styles using this package, but I do with my auto-generated. It's here https://github.com/hedefalk/atom-vue.

Anyway, I don't know the state of either my version or this version and I might have misunderstood, but  maybe we could merge it up.

Cheers,
Viktor

**Comment by miljan-aleksic** [comment]
I can confirm the HTML style issue and the fix in @hedefalk version. If the merge is out of question, why don't you publish your own package, @hedefalk?

**Comment by hedefalk** [comment]
@miljan-aleksic Since nothing heard here - sure! Just give me a reasonable name and I'll do it right away :)

**Comment by hedefalk** [comment]
Ok, so I figured this will be ok: https://atom.io/packages/language-vue

**Comment by miljan-aleksic** [comment]
Perfect :)
