### ISSUE TITLE
Publish latest version

### ISSUE THREAD

**Issue by karevn** [CYBAI/language-vue-component#3]
Can you please publish the latest version to the Atom repo? The one that is there currently does not handle `<template lang="jade">` correctly. I was able to fix it locally, but it's not good :)

**Comment by CYBAI** [comment]
Sorry that I can use my laptop till November, could you please fix it locally temporarily and I will fix this problem when I use my laptop!

**Comment by CYBAI** [comment]
@karevn Sorry for my late response, I've updated it to version 0.4.1, please check it out.
