### ISSUE TITLE
PHP syntax no longer working correctly after activate this plugin

### ISSUE THREAD

**Issue by kenng** [CYBAI/language-vue-component#4]
Once the plugin is activated, the php syntax highlight get override by it and left with almost no syntax highlight, except the opening tag "<".

**Comment by johannes-z** [comment]
+1, same issue

**Comment by CYBAI** [comment]
@kenng @johannes-z  I think I've fixed it, please check it again!

**Comment by kenng** [comment]
still same issue it seems

**Comment by CYBAI** [comment]
@kenng Could you take a picture to show me how it breaks? Do you just write `php` or write it in the vue component?
